### ISSUE TITLE
SpriteBuilder super slow when sprite is selected

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#1242]
When a sprite is selected on stage it is _very_ slow to move the timeline marker. It's possible that this is related to drawing/updating the the effects properties in the right hand property editor.

**Comment by thayerandrews** [comment]
I've been doing a little digging into this and it looks like the issue is the thumbnail resource previews that were added recently.  Here is an Instruments time profiler run on a build from the develop branch pulled yesterday afternoon:

![initial run annotated](https://cloud.githubusercontent.com/assets/400841/5510270/528f9fbe-8775-11e4-983a-2bbcbfd0f369.png)

As you can see from the heaviest stack trace during a slow drag, moving the time marker causes the following sequence of events: 
- The Inspector panel is updated
- The resource menus are populated
- The thumbnails are set for the menu items
- Per-pixel processing of the resource PNG is done to down-scale each image to thumbnail size

Commenting out the call to thumbnailImageForResource improves the situation dramatically though dragging with a sprite selected is still much slower than dragging without one selected.  This is demonstrated here:

![removed thumbnailimageforresource annotated](https://cloud.githubusercontent.com/assets/400841/5510272/58e63fc6-8775-11e4-8eb7-c9a15f335fb5.png)

In this second case it looks like the heaviest operation is now string drawing in NSTextFieldCell redraw.  I've not dug into this second case any further so I'm not sure which text field or fields are redrawing. Also, during other profiling runs I've seen different stack traces show up as heaviest. One of them was repeatedly reloading all the inspector control NIBs which seems non-optimal.

Putting all of this together I see a few things:
- Commit https://github.com/spritebuilder/SpriteBuilder/commit/c4fee53f6e21d1e930177798fa01caf9778a8774 
  which added preview thumbnails to the resource menus is the immediate cause of the slowdown AND...
- At first glance through this code path it seems that we are not caching the thumbnail images and we probably should be BUT...
- It also seems like we are doing too much work rebuilding the inspector pane with each update of the time marker.  Updating the time could change the values of visible inspector controls, but it doesn't seem like it could result in any controls being added or removed, the contents of menus changing, etc. However, it really looks like we're removing and rebuilding everything in the inspector pane with each change of the time value.

**Comment by thayerandrews** [comment]
Okay, I'm working on a possible fix for this issue which I've pushed [here](https://github.com/thayerandrews/SpriteBuilder/compare/issues/Fix1242). Instead of tearing down and rebuilding the inspector pane on every time marker move, I just refresh all of the current inspector properties.

This isn't ready for a pull request yet but if someone with more SB experience could take a look at it and let me know if I'm on the right track that would be great. Specifically, I want to make sure that there aren't any hidden gotchas to this new solution.  The old code has been in place forever so the pessimist in me assumes there must be some reason that it's never been changed.

The good news is that if this solution does work, it greatly improves performance. Here's an instruments run with the fix:

![refresh instead of rebuild annotated](https://cloud.githubusercontent.com/assets/400841/5513170/63e2d276-879e-11e4-9c5a-ddaefe4eefe8.png)

As you can see, dragging the time marker now has roughly the same performance cost no matter which node type is selected. Selecting different nodes still rebuilds the inspector pane and you can see the relative costs of different node types as the single spikes that occur before each drag region. Sprite is still very expensive because selecting it triggers the slow thumbnail creation path mentioned above.

**Comment by thayerandrews** [comment]
Here is the project I've been using for testing:

https://drive.google.com/file/d/0B7uVFeTINinAakZjbElxVUR1ZUE/view?usp=sharing

**Comment by thayerandrews** [comment]
I've filed pull request https://github.com/spritebuilder/SpriteBuilder/pull/1261 to address this issue.

**Comment by vlidholt** [comment]
I'm trying with a project with a bunch of images (still not a lot), just selecting a sprite still takes forever. I think we either need to remove the previews, or have another approach for generating them. E.g. caching them and/or generating them on a background thread.

**Comment by cocojoe** [comment]
One issue here is large files, I was just testing with the Lightning
project which features a 2.2MB Normal PNG.

We could create a thumbnail version when assets are added to SpriteBuilder
(and on preview for older projects), `resources-preview` or something along
those lines.

Another issue of course is lots of images, right now it's all brute force
and generates all folders however could delegate `NSMenu` to generate item
previews on demand per folder.

On 5 January 2015 at 20:43, Viktor Lidholt notifications@github.com wrote:

> I'm trying with a project with a bunch of images (still not a lot), just
> selecting a sprite still takes forever. I think we either need to remove
> the previews, or have another approach for generating them. E.g. caching
> them and/or generating them on a background thread.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spritebuilder/SpriteBuilder/issues/1242#issuecomment-68777442
> .

## 

Martin

**Comment by cocojoe** [comment]
I've improved the image generation method which has made large images pretty much instant now, will look at other optimisations in the morning.

**Comment by vlidholt** [comment]
I disabled the image preview feature in 1.4, we may want to figure this out for 2.0.

**Comment by NickyWeber** [comment]
@vlidholt Did you try @cocojoe's pull request? It was quite fast. even for hundreds of images after an initial loading time when opening the drop down for the first time.
